### ISSUE TITLE
Clarification on setup

### ISSUE THREAD

**Issue by Ergul** [skndungu/entry_monitor_system#2]
During the setup (first use of the system) the system is set as a wifi access point with a fixed wifi name / pass, see example here:
https://randomnerdtutorials.com/esp32-access-point-ap-web-server/
The system is configuration mode is acting as an HTTPS web server with a fixed IP 192.18.1.1 to let the user to send the REGISTER commands to declare himself to the main server and to get a sessionid used for all exchanges with the main server.
The system is powered via POE of course but will not use the Ethernet port until it is fully configured.
The command REGISTER may responds to HTTPS://192.168.1.1/register?server=test.profil.app&username=user&password=test&name=STAMP1&ip=192.168.50.1&location=Office
The system may define its fixed IP for the Ethernet port to the provided ip param.
The system may then execute the following HTTPS client request to declare himself to the main server:
https://test.profil.app/stamp/register?name=STAMP1&ip=192.168.50.1&location=Office&username=user&password=test
The ESP32 may store his name "STAMP1", his IP and location, then it may call the main server by executing the client  If the main server responds with success it may:
1) Store the returned sessionid in the ESP32 for ALL next request to be sent to the main server.
2) Store his name "STAMP1", ip "192.168.50.1" and location "Office"
3) All next message will have to be done thru the Ethernet port.

To make the  ESP32 as a HTTPS server: https://techtutorialsx.com/2019/04/08/esp32-https-server-handling-multiple-routes/

**Comment by skndungu** [comment]
I think all have been resolved on this issue
